"""add_buckets_to_settings

Revision ID: 43701b5ad37b
Revises: edffb021767e
Create Date: 2026-05-09 15:23:52.590031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43701b5ad37b'
down_revision: Union[str, Sequence[str], None] = 'edffb021767e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('buckets', sa.JSON(), server_default='[]', nullable=False), schema='pony_image')
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='pony_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='pony_image')
    op.drop_column('settings', 'buckets', schema='pony_image')
    # ### end Alembic commands ###
