"""add sha256 to storage

Revision ID: 6f6b26cb24c9
Revises: 8fe833703b5d
Create Date: 2026-05-09 12:10:24.864787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6b26cb24c9'
down_revision: Union[str, Sequence[str], None] = '8fe833703b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('sha256', sa.CHAR(length=64), nullable=False), schema='pony_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'sha256', schema='pony_image')
    # ### end Alembic commands ###
