"""initial schema

Revision ID: 8fe833703b5d
Revises: 
Create Date: 2026-05-01 18:54:41.299053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fe833703b5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=30), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('file_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('height > 0', name='image_height_chk'),
    sa.CheckConstraint('width > 0', name='image_width_chk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='image_sha256_uix'),
    schema='pony_image'
    )
    op.create_table('generation',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('styles', sa.Text(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('cfg', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('samplers', sa.Text(), nullable=True),
    sa.Column('scheduler', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['pony_image.image.id'], name='fk_generation_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', name='generation_image_id_uix'),
    schema='pony_image'
    )
    op.create_table('meta_data',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['pony_image.image.id'], name='fk_meta_data_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', name='meta_data_image_id_uix'),
    schema='pony_image'
    )
    op.create_table('review',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['pony_image.image.id'], name='fk_review_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', name='review_image_id_uix'),
    schema='pony_image'
    )
    op.create_table('storage',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('bucket', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['pony_image.image.id'], name='fk_storage_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', name='storage_image_id_uix'),
    schema='pony_image'
    )
    op.create_table('workflow',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sidecar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['pony_image.image.id'], name='fk_workflow_image_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', name='workflow_image_id_uix'),
    schema='pony_image'
    )
    op.create_table('lora',
    sa.Column('generation_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.Column('strength_model', sa.Float(), nullable=True),
    sa.Column('strength_clip', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['pony_image.generation.id'], name='fk_lora_generation_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='pony_image'
    )
    op.create_table('lora_image',
    sa.Column('lora_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lora_id'], ['pony_image.lora.id'], name='fk_lora_image_lora_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='pony_image'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lora_image', schema='pony_image')
    op.drop_table('lora', schema='pony_image')
    op.drop_table('workflow', schema='pony_image')
    op.drop_table('storage', schema='pony_image')
    op.drop_table('review', schema='pony_image')
    op.drop_table('meta_data', schema='pony_image')
    op.drop_table('generation', schema='pony_image')
    op.drop_table('image', schema='pony_image')
    # ### end Alembic commands ###
