"""add index on storage sha256

Revision ID: ec677a2f0757
Revises: 6f6b26cb24c9
Create Date: 2026-05-09 12:24:48.690912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec677a2f0757'
down_revision: Union[str, Sequence[str], None] = '6f6b26cb24c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pony_image_storage_sha256'), 'storage', ['sha256'], unique=False, schema='pony_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pony_image_storage_sha256'), table_name='storage', schema='pony_image')
    # ### end Alembic commands ###
