[pytest]
testpaths = tests
asyncio_mode = auto
addopts =
    --cov=api
    --cov=services
    --cov=utils
    --cov=dto
    --cov=models
    --cov=config
    --cov=storage
    --cov-report=term-missing
    --cov-report=html:reports/coverage
    --html=reports/test-report.html
    --self-contained-html
